FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install
RUN npx prisma generate

COPY . .

ENV NODE_ENV=test

CMD ["sh", "-c", "npx prisma migrate deploy && npx vitest run --reporter=verbose"]
